version: "3.8"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ~/.gbdx-config:/home/jovyan/.gbdx-config
      - .:/home/jovyan/notebooks/
